---
title: "Tarea4_paquetesR"
author: "Sthefanny Villa y Mishel Calero"
date: "2023-03-27"
output: html_document
---
```{r setup}
#Tarea 4
## Al menos 3 funciones distintas, al menos uno de ellos realiza una gráfica utilizando ggplot
#Funciones
###Existen varias funciones pre-cargadas en R las cuales puede ser utilizadas a la vez para esscribir nuevas funciones.Se tiene operaciones para las cuales no se tiene funciones definidas, por lo tanto deben ser escritas. Una función es un bloque de instrucciones que pueden ser utilizadas continuamente en un programa, es decir, permite automatizar operaciones. Generar funciones es más productivo que copiar y pegar las instrucciones cada vez que se necesita, por lo tanto tiene las siguientes ventajas:

###Se asigna un identificador que permite reconocer lo que realiza la función.

#*Se requiere pocos cambios, en general solamente los argumentos.

#*Se evita errores accidentales que pueden ocurrir al copiar y pegar.

#*Se puede utilizar para escribir nuevas funciones.

#*Se tiene una forma compacta para operar.

#*Facilita el aprendizaje del lenguaje de programación.

##Basicamente: La estructura de una función:

#"nombreFuncion <- function(argumento1, argumento2, ...){instruciones return(resultado)}"
```
```{r library}
library("devtools")
library("usethis")
library("testthat")
library("roxygen2")
library("datos")
```
```{r, ejemplo base}
cuadrado <- function(x)
  {y = x*exp(2) 
  return(y)}
cuadrado(2)
potencia <- function(x=2, y=1)
  {pot = x**y
  return(pot)}
potencia()

```
```{r}
#Install the latest version from [GitHub](https://github.com/gualapuromoises/residualR) as follow

# Install
if(!require(devtools)) install.packages("devtools")
devtools::install_github("gualapuromoises/residualR")

#Distribution
library(residualR)
#> Loading required package: ggplot2
# Create some data format
# :::::::::::::::::::::::::::::::::::::::::::::::::::
set.seed(1234)
potencia(3,2)
#> 9
```

# usethis::use_r("funcion1.R") ###crear la funcion
```{r}
Alumnos <- data.frame(
  Numero = paste("#",seq(1,10,by=2)),
  Edad = sample(15:18,10,TRUE),
  Calificacion = sample(1:10,10,TRUE),
  Genero = sample(c("Mujer", "Hombre"),10,TRUE),
  Materia = sample(c("Matematicas","Ciencias","Lengua", "Ingles"),10,TRUE))
Alumnos
promedio(Alumnos$Calificacion)
plot(Alumnos$Calificacion, 
     main = "Calificaciones", 
     type = 'h', col = rainbow(10), 
     bg="brown3", 
     xlim = c(0, 10), ylim = c(0, 10),
     xlab = "Estudiante", ylab = "Calificacion")
```
```{r, funcion #1}
source("funcion1.R")

```
```{r, funcion #2}
source("funcion2")
```
```{r, funcion #3}
source("funcion3")
```
